remote_theme: just-the-docs/just-the-docs
title: Pazetto
description: Especialista em Dados & ERP
color_scheme: dark  #Você pode apagar essa linha depois se preferir o tema claro (branco)
favicon_ico: "/assets/favicon.png"
logo: "/assets/logo.png"
